[book]
authors = ["jlikhuva"]
language = "en"
multilingual = false
src = "src"
title = "The Genetics of Neural Nets"

[preprocessor.katex]
after = ["links"]

[output.html]
additional-css = ["./theme/fonts/fonts.css"]